# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

{{- if .Values.features.activemqMonitor.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: activemq-exporter-config
  labels:
    app: activemq
data:
  config: |
    startDelaySeconds: 10
    hostPort: amq:1616
    ssl: false
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    includeObjectNames: ["org.apache.activemq:*","java.lang:type=OperatingSystem","java.lang:type=GarbageCollector,*","java.lang:type=Threading","java.lang:type=Runtime","java.lang:type=Memory","java.lang:name=*"]
    excludeObjectNames: ["org.apache.activemq:type=ColumnFamily,*"]
    autoExcludeObjectNameAttributes: true
    excludeObjectNameAttributes:
      "java.lang:type=OperatingSystem":
        - "ObjectName"
      "java.lang:type=Runtime":
        - "ClassPath"
        - "SystemProperties"
    rules:
    - pattern: ".*"  

---
apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  ports:
    - protocol: TCP
      port: 61616
      targetPort: 61616
  selector:
    app: activemq

---
apiVersion: v1
kind: Service
metadata:
  name: activemq-exporter
spec:
  ports:
    - protocol: TCP
      port: 5556
      targetPort: 5556
  selector:
    app: activemq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: activemq
          image: apache/activemq-classic:6.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 61616
              name: openwire
            - containerPort: 1616
              name: metrics 
          env:
            - name: ACTIVEMQ_SUNJMX_START
              value: "-Dcom.sun.management.jmxremote.port=1616 -Dcom.sun.management.jmxremote.rmi.port=1616 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"
            - name: ACTIVEMQ_BROKER_NAME
              value: "activemq-broker"
            - name: ACTIVEMQ_OPTS
              value: "-Xmx128m -Xms128m"  
        - name: activemq-exporter
          image: bitnami/jmx-exporter:0.20.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5556
              name: metrics
          volumeMounts:
            - name: activemq-exporter-config
              mountPath: /opt/bitnami/jmx-exporter/example_configs/httpserver_sample_config.yml
              subPath: config
      volumes:
        - name: activemq-exporter-config
          configMap:
            name: activemq-exporter-config

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: activemq-mock-client
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: mock-client
              image: apache/activemq-classic:6.0.1
              imagePullPolicy: IfNotPresent
              command: ["sh","-c","/opt/apache-activemq/bin/activemq producer --brokerUrl tcp://activemq:61616 --destination queue://testQueue --messageCount 50 --persistent true --message hello;/opt/apache-activemq/bin/activemq consumer --brokerUrl tcp://activemq:61616 --destination queue://testQueue --messageCount 10 --parallelThreads 2"]

{{- end }}
